server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVICE

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///E:/ums-iam-platform/backend/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/