spring:
  application:
    name: discovery-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${DISCOVERY_SERVICE_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
