global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ums-iam-platform'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authentication-service:8086']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'authorization-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authorization-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8085']

  - job_name: 'organization-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['organization-service:8087']

  - job_name: 'admin-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin-service:8088']

  - job_name: 'audit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['audit-service:8089']
