import {
  Activity,
  AppWindow,
  BadgeCheck,
  Bell,
  Building2,
  ClipboardCheck,
  FileClock,
  FileKey2,
  Fingerprint,
  Gauge,
  GitBranch,
  Globe2,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  Link2,
  LockKeyhole,
  Network,
  RadioTower,
  ScrollText,
  ShieldCheck,
  ShieldQuestion,
  SlidersHorizontal,
  UserCog,
  Users,
  Workflow,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { AdminCapability } from "../../lib/auth/capabilities";

export type ScreenStatus = "Live starter" | "Blueprint" | "Roadmap";

export type ScreenBlueprint = {
  title: string;
  path: string;
  section: string;
  status: ScreenStatus;
  icon: LucideIcon;
  summary: string;
  primaryActions: string[];
  dataSources: string[];
  widgets: string[];
  hasCustomStarter?: boolean;
  requiredCapability?: AdminCapability;
};

export const screenBlueprints: ScreenBlueprint[] = [
  {
    title: "Dashboard",
    path: "/dashboard",
    requiredCapability: "dashboard.read",
    section: "Command Center",
    status: "Live starter",
    icon: LayoutDashboard,
    summary: "Executive IAM health, user activity, privilege risk, and service status.",
    primaryActions: ["Review risk", "Export report", "Open audit trail"],
    dataSources: ["GET /api/v1/admin/dashboard"],
    widgets: ["KPI summary", "Recent events", "Risk queue", "Service health"],
    hasCustomStarter: true,
  },
  {
    title: "Users",
    path: "/users",
    requiredCapability: "users.read",
    section: "Directory",
    status: "Live starter",
    icon: Users,
    summary: "Search, filter, inspect, and administer user lifecycle state.",
    primaryActions: ["Create user", "Bulk import", "Suspend selected"],
    dataSources: ["GET /api/v1/admin/users"],
    widgets: ["User table", "Lifecycle filters", "Entitlement chips", "User drawer"],
    hasCustomStarter: true,
  },
  {
    title: "User Lifecycle",
    path: "/users/lifecycle",
    section: "Directory",
    status: "Blueprint",
    icon: UserCog,
    summary: "Invitation, activation, lock, suspension, deprovisioning, and restoration workflows.",
    primaryActions: ["Invite user", "Force reset", "Deprovision"],
    dataSources: ["Target: user-service lifecycle APIs", "Target: auth session revocation APIs"],
    widgets: ["State timeline", "Admin actions", "Reason capture", "Session impact"],
  },
  {
    title: "Organizations",
    path: "/organizations",
    requiredCapability: "organizations.read",
    section: "Tenancy",
    status: "Live starter",
    icon: Building2,
    summary: "Tenant records, membership health, lifecycle, quotas, and settings.",
    primaryActions: ["Create tenant", "Suspend tenant", "Export tenant data"],
    dataSources: ["Target: organization-service organizations APIs"],
    widgets: ["Tenant table", "Plan and quota cells", "Lifecycle controls", "Membership count"],
    hasCustomStarter: true,
  },
  {
    title: "Domains",
    path: "/organizations/domains",
    section: "Tenancy",
    status: "Roadmap",
    icon: Globe2,
    summary: "Domain verification, federation routing, and ownership evidence.",
    primaryActions: ["Add domain", "Verify DNS", "Remove domain"],
    dataSources: ["Target: organization domain APIs"],
    widgets: ["DNS challenge", "Verification status", "Provider routing", "Audit evidence"],
  },
  {
    title: "Org Units",
    path: "/organizations/units",
    section: "Tenancy",
    status: "Roadmap",
    icon: GitBranch,
    summary: "Departments, teams, hierarchy, and scoped administration boundaries.",
    primaryActions: ["Create unit", "Move unit", "Assign members"],
    dataSources: ["Target: organization unit APIs"],
    widgets: ["Hierarchy tree", "Unit details", "Membership panel", "Scoped admins"],
  },
  {
    title: "Role Assignments",
    path: "/roles/assignments",
    requiredCapability: "roles.manage",
    section: "Access Control",
    status: "Live starter",
    icon: BadgeCheck,
    summary: "Assign roles to users and review privilege grants.",
    primaryActions: ["Assign role", "Revoke grant", "Require approval"],
    dataSources: ["POST /api/v1/admin/roles/assign"],
    widgets: ["Assignment form", "Grant table", "Scope selector", "Expiry field"],
    hasCustomStarter: true,
  },
  {
    title: "Roles",
    path: "/roles",
    requiredCapability: "roles.read",
    section: "Access Control",
    status: "Live starter",
    icon: ShieldCheck,
    summary: "Platform, tenant, and application roles with scoped permissions.",
    primaryActions: ["Create role", "Clone role", "Archive role"],
    dataSources: ["GET /api/v1/admin/roles"],
    widgets: ["Role catalog", "Permission matrix", "Scope labels", "Usage impact"],
    hasCustomStarter: true,
  },
  {
    title: "Permissions",
    path: "/permissions",
    requiredCapability: "roles.read",
    section: "Access Control",
    status: "Live starter",
    icon: FileKey2,
    summary: "Stable resource-action permission inventory and ownership.",
    primaryActions: ["Create permission", "Import permissions", "Mark deprecated"],
    dataSources: ["GET /api/v1/admin/permissions"],
    widgets: ["Resource grouping", "Action grid", "Code stability", "Role usage"],
    hasCustomStarter: true,
  },
  {
    title: "Access Grants",
    path: "/grants",
    requiredCapability: "roles.read",
    section: "Access Control",
    status: "Live starter",
    icon: BadgeCheck,
    summary: "Admin-wide entitlement inventory for user, role, organization, and scope grants.",
    primaryActions: ["Filter grants", "Revoke grant", "Inspect source"],
    dataSources: ["GET /api/v1/admin/grants", "DELETE /api/v1/admin/grants/{grantId}"],
    widgets: ["Grant table", "Principal filters", "Scope labels", "Revoke actions"],
    hasCustomStarter: true,
  },
  {
    title: "Groups",
    path: "/groups",
    section: "Access Control",
    status: "Roadmap",
    icon: Network,
    summary: "Directory groups, nested membership, and derived access.",
    primaryActions: ["Create group", "Add members", "Detect cycles"],
    dataSources: ["Target: authorization-service groups APIs"],
    widgets: ["Group table", "Nested graph", "Member search", "Derived grants"],
  },
  {
    title: "Policies",
    path: "/policies",
    section: "Access Control",
    status: "Roadmap",
    icon: SlidersHorizontal,
    summary: "ABAC/ReBAC policy sets, conditions, priorities, and explainable decisions.",
    primaryActions: ["Create policy", "Test policy", "Activate version"],
    dataSources: ["Target: authorization policy APIs"],
    widgets: ["Policy editor", "Condition builder", "Decision tester", "Version history"],
  },
  {
    title: "Access Requests",
    path: "/governance/access-requests",
    section: "Governance",
    status: "Roadmap",
    icon: Workflow,
    summary: "Requested access, approvals, justifications, expiry, and revocation work.",
    primaryActions: ["Request access", "Approve", "Deny"],
    dataSources: ["Target: authorization governance APIs"],
    widgets: ["Approval queue", "Request form", "Beneficiary context", "SLA counters"],
  },
  {
    title: "Access Reviews",
    path: "/governance/access-reviews",
    section: "Governance",
    status: "Roadmap",
    icon: ClipboardCheck,
    summary: "Certification campaigns for managers, app owners, and security admins.",
    primaryActions: ["Start campaign", "Certify", "Revoke"],
    dataSources: ["Target: access review campaign APIs"],
    widgets: ["Campaign cards", "Reviewer queue", "Decision grid", "Evidence export"],
  },
  {
    title: "Break Glass",
    path: "/governance/break-glass",
    section: "Governance",
    status: "Roadmap",
    icon: ShieldQuestion,
    summary: "Emergency privileged access with approval, expiry, and enhanced audit.",
    primaryActions: ["Request access", "Activate", "Revoke"],
    dataSources: ["Target: break-glass grant APIs"],
    widgets: ["Active grants", "Approval trail", "Expiry timers", "Security alerts"],
  },
  {
      title: "Sessions",
      path: "/operations/sessions",
    requiredCapability: "sessions.read",
      section: "Operations",
      status: "Live starter",
    icon: Activity,
    summary: "User sessions, devices, refresh-token families, and forced revocation.",
    primaryActions: ["Revoke session", "Revoke all", "Mark trusted"],
    dataSources: ["GET /api/v1/admin/sessions", "POST /api/v1/admin/sessions/{sessionId}/revoke"],
    widgets: ["Session table", "Device metadata", "Token family state", "Risk score"],
    hasCustomStarter: true,
  },
  {
    title: "MFA",
    path: "/authentication/mfa",
    section: "Authentication",
    status: "Roadmap",
    icon: Fingerprint,
    summary: "TOTP, WebAuthn, recovery codes, enrollment policy, and recovery controls.",
    primaryActions: ["Require MFA", "Reset authenticator", "Generate recovery codes"],
    dataSources: ["Target: authenticator APIs"],
    widgets: ["Enrollment coverage", "Authenticator list", "Recovery audit", "Policy gaps"],
  },
  {
    title: "OAuth Clients",
    path: "/authentication/oauth-clients",
    section: "Authentication",
    status: "Roadmap",
    icon: AppWindow,
    summary: "OIDC/OAuth clients, redirects, grants, scopes, secrets, and consent.",
    primaryActions: ["Register client", "Rotate secret", "Disable client"],
    dataSources: ["Target: OAuth client administration APIs"],
    widgets: ["Client catalog", "Redirect list", "Secret rotation", "Allowed scopes"],
  },
  {
    title: "Federation",
    path: "/authentication/federation",
    section: "Authentication",
    status: "Roadmap",
    icon: Link2,
    summary: "Tenant OIDC/SAML providers, metadata rotation, and home realm discovery.",
    primaryActions: ["Add provider", "Test login", "Rotate metadata"],
    dataSources: ["Target: federation provider APIs"],
    widgets: ["Provider cards", "Domain routing", "Certificate status", "JIT settings"],
  },
  {
    title: "Signing Keys",
    path: "/authentication/signing-keys",
    section: "Authentication",
    status: "Roadmap",
    icon: KeyRound,
    summary: "JWKS, key activation windows, retirement, and rotation evidence.",
    primaryActions: ["Create key", "Activate", "Retire"],
    dataSources: ["Target: signing key APIs", "Target: JWKS endpoint"],
    widgets: ["Key timeline", "Kid inventory", "Rotation warnings", "Consumer status"],
  },
  {
    title: "SCIM",
    path: "/provisioning/scim",
    section: "Provisioning",
    status: "Roadmap",
    icon: RadioTower,
    summary: "SCIM users, groups, schemas, service provider config, and sync evidence.",
    primaryActions: ["Create token", "Run sync", "View failures"],
    dataSources: ["Target: SCIM 2.0 APIs"],
    widgets: ["Provisioning jobs", "Schema browser", "Failure queue", "ETag state"],
  },
  {
    title: "Service Accounts",
    path: "/provisioning/service-accounts",
    section: "Provisioning",
    status: "Roadmap",
    icon: LockKeyhole,
    summary: "Machine identities, scoped credentials, rotation, and last-used telemetry.",
    primaryActions: ["Create service account", "Rotate credential", "Disable"],
    dataSources: ["Target: service account APIs"],
    widgets: ["Credential table", "Scope review", "Rotation reminders", "Usage graph"],
  },
  {
    title: "Notifications",
    path: "/notifications",
    section: "Operations",
    status: "Blueprint",
    icon: Bell,
    summary: "Templates, delivery attempts, suppressions, preferences, and webhooks.",
    primaryActions: ["Create template", "Retry delivery", "Add webhook"],
    dataSources: ["Target: notification-service APIs"],
    widgets: ["Template list", "Delivery log", "Suppression table", "Webhook status"],
  },
  {
    title: "Audit Logs",
    path: "/audit/logs",
    requiredCapability: "audit.read",
    section: "Evidence",
    status: "Live starter",
    icon: ScrollText,
    summary: "Searchable admin and security activity evidence.",
    primaryActions: ["Filter", "Export", "Open detail"],
    dataSources: ["GET /api/v1/admin/audit/logs"],
    widgets: ["Event table", "Outcome filters", "Actor search", "Correlation IDs"],
    hasCustomStarter: true,
  },
  {
    title: "Audit Exports",
    path: "/audit/exports",
    section: "Evidence",
    status: "Roadmap",
    icon: FileClock,
    summary: "Signed exports, legal hold, retention policy, and SIEM delivery.",
    primaryActions: ["Create export", "Download", "Send to SIEM"],
    dataSources: ["Target: audit export APIs", "Target: SIEM destination APIs"],
    widgets: ["Export jobs", "Checksums", "Retention rules", "Delivery offsets"],
  },
  {
    title: "System Health",
    path: "/operations/health",
    section: "Operations",
    status: "Blueprint",
    icon: Gauge,
    summary: "Gateway, service, queue, database, and config health for IAM operators.",
    primaryActions: ["Open service", "Acknowledge alert", "View runbook"],
    dataSources: ["Target: actuator health", "Target: metrics gateway"],
    widgets: ["Service grid", "Queue depth", "Error budget", "Recent incidents"],
  },
  {
    title: "Security Settings",
    path: "/settings/security",
    section: "Settings",
    status: "Roadmap",
    icon: Landmark,
    summary: "Tenant password, MFA, session, federation, and admin step-up policy.",
    primaryActions: ["Update policy", "Preview impact", "Require step-up"],
    dataSources: ["Target: organization security policy APIs"],
    widgets: ["Policy tabs", "Risk preview", "Exception list", "Change audit"],
  },
  {
    title: "Support Tools",
    path: "/operations/support",
    section: "Operations",
    status: "Blueprint",
    icon: LifeBuoy,
    summary: "Low-risk diagnostics for account recovery, investigation, and operator handoff.",
    primaryActions: ["Lookup subject", "Copy context", "Create handoff"],
    dataSources: ["Target: read-only diagnostic APIs"],
    widgets: ["Subject lookup", "Recent auth history", "Entitlement snapshot", "Notes"],
  },
];

export const sidebarSections = Array.from(
  screenBlueprints.reduce((sections, screen) => {
    const screens = sections.get(screen.section) ?? [];
    screens.push(screen);
    sections.set(screen.section, screens);
    return sections;
  }, new Map<string, ScreenBlueprint[]>()),
).map(([section, screens]) => ({ section, screens }));
