server:
  port: 8084

spring:
  application:
    name: ADMIN-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/admin_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update