server:
  port: 8080

jwt:
  public-key: ${JWT_PUBLIC_KEY:}
  public-key-path: ${JWT_PUBLIC_KEY_PATH:keys/public.pem}
  issuer: ums-iam-platform
  audience: ${JWT_AUDIENCE:ums-api-gateway}

internal:
  gateway:
    secret: ${INTERNAL_GATEWAY_SECRET:local-dev-gateway-secret-change-me}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  cloud:
    gateway:
      routes:
        - id: authentication-public
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
        - id: authentication-admin-sessions
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/admin/sessions/**,/api/v1/admin/users/*/sessions/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/v1/organizations/**
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/api/v1/authorization/**,/api/v1/roles/**,/api/v1/permissions/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**,/api/v1/templates/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/hrms/employees/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/v1/admin/**
        - id: audit-events
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/audit/events/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - http://127.0.0.1:5174
              - http://localhost:5174
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
