server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/audit_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  public-key-path: classpath:keys/public.pem
  issuer: ums-auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info