server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: root
    password: root

  rabbitmq:
    host: rabbitmq
    port: 5672

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

jwt:
  private-key-path: keys/private_key.pem
  public-key-path: keys/public_key.pem
  issuer: ums-iam-platform
  access-token-expiry-ms: 900000
  refresh-token-expiry-ms: 604800000